### ISSUE TITLE
第12章-勘误列表汇总

### ISSUE THREAD

**Issue by zhongzunfa** [SpringCloud/spring-cloud-code#6]
## apollo配置zuul 配置下发问题更正
1、对于12章中的zuul 网关配置更新下发，图12-48 多了一个等号， 正确的配图如下：
![wechatimg59](https://user-images.githubusercontent.com/14095698/45950901-194b5580-c034-11e8-974e-8a4beb946caf.jpeg)

2、兼容apollo发布版, 案例配置文件中添加一个meta 的地址， 具体如下所示：
```
apollo:
  bootstrap:
    enabled: true
    namespaces: application
  meta: http://localhost:8080
```

推荐看案例源代码配置项；
